title: Elena de Sus

header_pages: 
 - aboutme.md

author: Málaga
email: elena@ctxt.es

description: > # this means to ignore newlines until "baseurl:"
  Periodista y editora. En la redacción de CTXT.
# social links
twitter_username:  elena_sg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

lang: es

theme: minima
